os: linux
dist: bionic
language: node_js
node_js:
  - "10"
jobs:
  include:
    - name: Lint
      script: npm run lint
    - name: Test
      script: npm test
    - name: Build & Deploy
      script: if [ "$TRAVIS_BRANCH" == "master" ]; then npm run build:prod; else npm run build; fi
      before_deploy:
        - echo "Deploying!"
      deploy:
        - provider: firebase
          skip_cleanup: true
          on:
            branch: master
          project: devfestmaputo
          token:
            secure: "BNFz29kPtvxh6+LEdveHGbMcdbvQJ+RoUtuqcDai2vBkL5XBxfF4Tqeat+TsPRqP1hBi6OkiJn3WwVLdY4j7bQoIByHq5gVa3G/sWy5O2MRceIoEWKb7aK0jsnzItzI0+nR4BcyBGMEWInNi0bI3IYgDAw1NXm859qyexBuc0msHjyIxvp2gClk+KgFfAs5Ko+sT/LQss6WlrwsyoreT+9mWHVlSsQBtYqbFb0OZnp3c1RPupCjO3IgLfkQPbKaW1Zt6185geC1HpPRuUr40ZHGwQj/FxB0/mTMxXAVVYZ5p++9VmL6Lmej/NLx4vU+Dy2zIpN4lpAWFcq6onfEAMB3aSg6s8BmdewR7Ilivb9KejZp/XXDxC12danRLEkYaMTuTRfFBT+5N9NutbFfqUqOSdKZKJvAKd87YMb3ArvaGAbhcdUgmQO7O7da+3HVLTh6F/RaHqCYlNDdIFZk3iMTfAXeALvsLXC1Z6NS6ltCiv+1BUtFGVHVhAmlh3BND3ADGnhqtBEx65DsfN6SKLG4QQWJsKnfu3MtSu9hk6Ebpdjk1AaGOVjevdN1/B41Zs6Qm7T1+Bl6Cq+R3TP/2nTp7G2s7TSRivGIsHsCLbosKqa+uxjnvUNjo4Lg0fckLDrg0SE2RalA2Hx2L119AIOqtv8my2SZ6rKuKZaWVUuA="
